baseurl = "https://www.freeanalystnotes.com//"  # Include trailing slash# "https://epic-brattain-a9e0eb.netlify.com//"  # Include trailing slash
title = "Free Analyst Notes"
theme = "hugo-swift-theme"
author = "Free Analyst Notes"
copyright = "Copyright 2020, Invest-With-R; all rights reserved."
canonifyurls = true
paginate = 4
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
[params]
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57

# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

